function initialise_db( db_handle )
%INITIALISE_DB sets up the database before we start registering  a batch of songs

    exists = sqlite3.execute(db_handle, ...
                             ['SELECT count(*) FROM sqlite_master '...
                              'WHERE type=''table'' AND name=''hashes''']);

    if(exists.count ~= 1)
         sqlite3.execute(db_handle, ...
                         ['CREATE TABLE IF NOT EXISTS '...
                          'songs (song_id INTEGER PRIMARY KEY AUTOINCREMENT, '...
                                 'song_name VARCHAR)']);

         sqlite3.execute(db_handle, ...
                         ['CREATE TABLE IF NOT EXISTS '...
                          'hashes (song_id INTEGER, '...
                                  'hash INTEGER, '...
                                  'hash_number INTEGER)']);


         sqlite3.execute(db_handle, ...
                         'CREATE INDEX songname_index ON songs(song_name)');
    end

     % Drop our hash index to improve speed (we'll re-make it at the
     % end)
     sqlite3.execute(db_handle, ...
                     'DROP INDEX IF EXISTS hash_index');
                 
end

