function [set, len, succ, tot] = run_passthrough_tests_batch ...
                            (match_file_function, ...
                             get_song_name_function, ...
                             database_filename, ...
                             test_clips_base_folder, ...
                             input_folder_base, ...
                             scoring_mode, ...
                             clip_lengths)

    m = 1;
    i = 1;
    files = dir(input_folder_base);
    
    
    
     for folder = files'
        if(folder.isdir && ~strcmp(folder.name, '.') && ~strcmp(folder.name, '..'))
            
            foldername = [input_folder_base folder.name '/'];
            
            for this_length = clip_lengths

                test_clips_folder       = [test_clips_base_folder ...
                                           num2str(this_length) 'sec/'];
    
    
                [matched, total] = testing.run_passthrough_tests ...
                                              (match_file_function, ...
                                               get_song_name_function, ...
                                               database_filename, ...
                                               test_clips_folder, ...
                                               foldername, ...
                                               scoring_mode, ...
                                               this_length, ...
                                               m);

                len(i) = this_length;
                succ(i) = matched;
                tot(i) = total;
                set(i) = folder.name;

                i = i + 1;
            end
        end
     end
     
    
end