function [set, snr, len, succ, tot] = run_natural_noise_batch ...
                                            (snrs, ...
                                             lengths, ...
                                             database_filename, ...
                                             match_file_function, ...
                                             get_song_name_function, ...
                                             input_folder_base, ...
                                             test_clips_base_folder, ...
                                             scoring_mode, ...
                                             noise_filename)
%RUN_NATURAL_NOISE_BATCH runs natural noise tests for all combinations of
%the given values for snr and clip length, for each folder in the
%input_folder_base
%   snrs should be an array of snr ratios in dB
%   lengths should be an array of clip lengths in seconds

    m = 1;
    i = 1;
    files = dir(input_folder_base);
    
    
    for folder = files'
        if(folder.isdir && ~strcmp(folder.name, '.') && ~strcmp(folder.name, '..'))
            
            foldername = [input_folder_base folder.name '/'];
            
            for this_snr = snrs
                for this_length = lengths

                    test_clips_folder       = [test_clips_base_folder ...
                                               num2str(this_length) 'sec/'...
                                               num2str(this_snr) 'db/'];

                    [r, t] = testing.run_natural_noise_tests(match_file_function, ...
                                                             get_song_name_function, ...
                                                             database_filename, ...
                                                             test_clips_folder, ...
                                                             foldername, ...
                                                             scoring_mode, ...
                                                             this_length, ...
                                                             m, ...
                                                             this_snr, ...
                                                             noise_filename);

                    snr(i) = this_snr;
                    len(i) = this_length;
                    succ(i) = r;
                    tot(i) = t;
                    set(i) = folder.name;

                    i = i + 1;

                end
            end
            
        end
    end
    
end

