function [snr, len, succ, tot] = run_gaussian_batch(snrs, ...
                                                    lengths, ...
                                                    database_filename, ...
                                                    match_file_function, ...
                                                    get_song_name_function, ...
                                                    input_folder, ...
                                                    test_clips_base_folder, ...
                                                    scoring_mode, ...
                                                    m)
%RUN_GAUSSIAN_BATCH runs gaussian tests for all combinations of the given
%values for snr and clip length. 
%   snrs should be an array of snr ratios in dB
%   lengths should be an array of clip lengths in seconds

    i = 1;
    
    for this_snr = snrs
        for this_length = lengths
            
            test_clips_folder       = [test_clips_base_folder ...
                                       num2str(this_length) 'sec/'...
                                       num2str(this_snr) 'db/'];

            [r, t] = testing.run_gaussian_tests(match_file_function, ...
                                                get_song_name_function, ...
                                                database_filename, ...
                                                test_clips_folder, ...
                                                input_folder, ...
                                                scoring_mode, ...
                                                this_length, ...
                                                m, ...
                                                this_snr);
            
            snr(i) = this_snr;
            len(i) = this_length;
            succ(i) = r;
            tot(i) = t;
            
            i = i + 1;
            
        end
    end

    
end

